### ISSUE TITLE
Export _site directory

### ISSUE THREAD

**Issue by royfrancis** [Starefossen/docker-github-pages#69]
This works great to run the site in my browser. But, how do I modify it such it exports `_site` directory from the container into my host working directory?

**Comment by bredd** [comment]
I had the same problem and just solved it. You need to add `./_site:/_site` to the volumes section of your docker-compose.yml file.

Here's how mine reads:

```yaml
version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    environment:
      - "JEKYLL_GITHUB_TOKEN:"
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app:rw
      - ./_site:/_site
    tty: true
```
