### ISSUE TITLE
I only see listing of my deployed folder, not the website.

### ISSUE THREAD

**Issue by joergi** [Starefossen/docker-github-pages#70]
If i deploy my jeykll gh-page blog with github, it works fine.
the code is [here](4d93afb78c28ae40e539ed7657b1eb5efb798924), the blog is [here](https://blog.joergi.io/)

I also added the docker-compose.yml file to my project.
```
version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    environment:
      - "JEKYLL_GITHUB_TOKEN: MY_TOKEN_XXXXX"
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    tty: true

# file from https://github.com/Starefossen/docker-github-pages
```

the server get's deployed, but I only see this: 
![image](https://user-images.githubusercontent.com/1439809/96641230-b583db80-1324-11eb-87a9-8e8e60539dbc.png)
This is the structure of the deployed server with all tags and topics...
but I can't see the website itself.

in the online version the [default.html](https://github.com/joergi/blog/blob/main/_layouts/default.html) takes care of the deployment.

I have no idea, what I need to change, that it works locally too (because at the moment I'm always doing try'n'error on the live version 

Thanks for your help @Starefossen !
